### ISSUE TITLE
Не получилось установить слушатель событий на кнопки из java кода.

### ISSUE THREAD

**Issue by MaiklGureev** [RedMadRobot/PINkman#15]
Попробовал поставить обычный слушатель для view OnKeyListener и OnClickListener.

![изображение](https://user-images.githubusercontent.com/35026973/98636373-26c11800-2340-11eb-926b-6f84920c3573.png)

![изображение](https://user-images.githubusercontent.com/35026973/98637149-7f44e500-2341-11eb-8723-877470bb59da.png)

![изображение](https://user-images.githubusercontent.com/35026973/98636435-47896d80-2340-11eb-8995-8ab644aad4ce.png)

**Comment by Fi5t** [comment]
Спасибо за информацию! При разработке не учел, что кто-то будет использовать этот UI из Java. Исправлю в ближайшее время.
