### ISSUE TITLE
Avoid resource naming conflicts

### ISSUE THREAD

**Issue by osipxd** [RedMadRobot/PINkman#2]
Better to add a namespace prefix to library resources. In this case, it will be something like `pinkman_darkGray`.  
A developer can define the resource with the same name in his app and get pin view changed unexpectedly. Prefix avoids such cases.
https://github.com/RedMadRobot/PINkman/blob/05e076bcd06e234622d432fb7c0958f8f2893111/pinkman-ui/src/main/res/values/colors.xml#L3-L4

The same here. Better to add a prefix. For example `<style name="Pinkman.DefaultKeyboard" parent="">`
https://github.com/RedMadRobot/PINkman/blob/05e076bcd06e234622d432fb7c0958f8f2893111/pinkman-ui/src/main/res/values/styles.xml#L2

The same for the drawables.
`circle_red` -> `pinkman_circle_red`
`circle_grey` -> `pinkman_circle_grey`

**Comment by Fi5t** [comment]
@osipxd yeah, you're right. Feel free to send PR ;)
