### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by osipxd** [RedMadRobot/PINkman#4]
Will pin be lost after an update from Android M to O?

https://github.com/RedMadRobot/PINkman/blob/05e076bcd06e234622d432fb7c0958f8f2893111/pinkman/src/main/java/com/redmadrobot/pinkman/internal/Pbkdf2Factory.kt#L11-L17

**Comment by Fi5t** [comment]
No. This algorithm is also stored and used when a key calculated

```kotlin
internal data class Pbkdf2Key(
    val algorithm: String, // <---
```

```kotlin
        val storedKey = loadKeyFromStorage()

        val inputKey = Pbkdf2Factory.createKey(
            inputPin.toCharArray(),
            storedKey.salt,
            storedKey.algorithm, // <---
            storedKey.iterations
        )
```

**Comment by osipxd** [comment]
Ok
