### ISSUE TITLE
Call Pinkman on computation thread

### ISSUE THREAD

**Issue by osipxd** [RedMadRobot/PINkman#5]
Operations `createPin`, `changePin`, `isValidPin`, etc may take some time.  
I think these operations shouldn't be run on the main thread. A developer can manage which thread to use himself but it would be great to have Rx wrapper around Pinkman or something like.

**Comment by Fi5t** [comment]
I haven't been planning to add Rx support to this library, but if there is "community request" I'll consider this ability. You can use a `defer` operator to deal with it now.

**Comment by osipxd** [comment]
It easily can be done in a separated library. So people who don't need Rx can avoid it as a dependency.
